version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  #backend:
   
   # build: .
    #env_file: .env
    #ports:
     # - "4000:4000"
    #volumes:
     # - ./:/usr/src/app
      #- /usr/src/app/node_modules
    #depends_on:
     # postgres:
      #  condition: service_healthy
    #environment:
     # - NODE_ENV=development
      #- POSTGRES_HOST=postgres
      #- POSTGRES_PORT=5432
    # command: sh -c "npm install && npm run dev"
    #restart: unless-stopped

  # --- Servicio de Hasura ---
  hasura:
    image: hasura/graphql-engine:v2.33.0
    ports:
      - "8080:8080"  # Puerto para la consola web
    env_file: .env  # Reutiliza el mismo .env para las variables
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@backend-postgres-1:5432/${POSTGRES_DB}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"  # Habilita la interfaz web
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"  # Clave para acceder (debes agregarla al .env)
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "${JWT_SECRET}"}'  # Opcional: si usas JWT
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: